In [1]:
# import os
# import sys
# module_path = os.path.abspath(os.path.join('..'))
# if module_path not in sys.path:
#     sys.path.append(module_path)
import cProfile

In [2]:
import numpy as np
from pprint import pprint

In [3]:
import ccd
import test
from test.shared import sample_line, sample_sinusoid, read_data
import ccd.procedures as change
from ccd.models import lasso

In [4]:
def test_validate_sample_2_detection_results():
    """ Sample 2 contains two changes and should test the full path through
    the algorithm"""
    data = read_data("test/resources/sample_WA_grid08_row999_col1_normal.csv")
    results = ccd.detect(data[0], data[1], data[2], data[3], data[4],
                         data[5], data[6], data[7], data[8])
    print(len(results['change_models']))

In [ ]:
test_validate_sample_2_detection_results()

2017-01-07 11:11:45 procedures::fit_procedure        - [62 ]Procedure selected: standard_procedure
2017-01-07 11:11:45 procedures::standard_procedure   - [216]Build change models – dates: 724, obs: (7, 724), meow_size: 12, peek_size: 6
2017-01-07 11:11:45 procedures::standard_procedure   - [228]Processing mask initial count: 477
2017-01-07 11:11:45 procedures::standard_procedure   - [244]Variogram values: [  95.    95.5  133.   315.   199.   152.   395. ]
2017-01-07 11:11:45 procedures::standard_procedure   - [249]Initialize for change model #: 1
2017-01-07 11:11:45 change    ::initialize           - [278]Initial slice(0, 12, None)
2017-01-07 11:11:45 change    ::find_time_index      - [159]Sufficient time from times[0..12] (day #724746 to #725114)
2017-01-07 11:11:45 change    ::initialize           - [288]Checking window: slice(0, 12, None)
2017-01-07 11:11:45 change    ::initialize           - [296]Number of Tmask outliers found: 0
2017-01-07 11:11:45 change    ::initialize         

In [ ]:
a = np.arange(10).reshape(2, -1)
print(a ** 2)
print(np.sum(a ** 2, axis=0))

[[ 0  1  4  9 16]
 [25 36 49 64 81]]
[25 37 53 73 97]
